using Newtonsoft.Json;

namespace PayCheckServerLib.Jsons {
	public class OrderPostBody {
		[JsonProperty("itemId")]
		public string ItemId { get; set; }
		[JsonProperty("quantity")]
		public int Quantity { get; set; }
		[JsonProperty("price")]
		public int Price { get; set; }
		[JsonProperty("discountedPrice")]
		public int DiscountedPrice { get; set; }
		[JsonProperty("currencyCode")]
		public string CurrencyCode { get; set; }
		[JsonProperty("region")]
		public string Region { get; set; }
		[JsonProperty("language")]
		public string Language { get; set; }
		[JsonProperty("returnUrl")]
		public string ReturnURL { get; set; }
	}
	// Could be wrong, was autogenerated
	public class Order {
		public partial class CurrencyJson {
			[JsonProperty("currencyCode")]
			public string CurrencyCode { get; set; }
			[JsonProperty("currencySymbol")]
			public string CurrencySymbol { get; set; }
			[JsonProperty("currencyType")]
			public string CurrencyType { get; set; }
			[JsonProperty("namespace")]
			public string Namespace { get; set; }
			[JsonProperty("decimals")]
			public int Decimals { get; set; }
		}
		// could be replaced by ItemDefinitionJson, but unsure if it'd cause problems
		public partial class ItemSnapshotJson {
			[JsonProperty("itemId")]
			public string ItemId { get; set; }
			[JsonProperty("baseAppId")]
			public string BaseAppId { get; set; }
			[JsonProperty("sku")]
			public string Sku { get; set; }
			[JsonProperty("namespace")]
			public string Namespace { get; set; }
			[JsonProperty("name")]
			public string Name { get; set; }
			[JsonProperty("listable")]
			public bool Listable { get; set; }
			[JsonProperty("purchasable")]
			public bool Purchasable { get; set; }
			[JsonProperty("entitlementType")]
			public string EntitlementType { get; set; }
			[JsonProperty("itemType")]
			public string ItemType { get; set; }
			[JsonProperty("title")]
			public string Title { get; set; }
			[JsonProperty("maxCountPerUser")]
			public int MaxCountPerUser { get; set; }
			[JsonProperty("maxCount")]
			public int MaxCount { get; set; }
			[JsonProperty("region")]
			public string Region { get; set; }
			[JsonProperty("language")]
			public string Language { get; set; }
			[JsonProperty("createdAt")]
			public string CreatedAt { get; set; }
			[JsonProperty("updatedAt")]
			public string UpdatedAt { get; set; }
		}
		[JsonProperty("orderNo")]
		public string OrderNo { get; set; }
		[JsonProperty("namespace")]
		public string Namespace { get; set; }
		[JsonProperty("userId")]
		public string UserId { get; set; }
		[JsonProperty("itemId")]
		public string ItemId { get; set; }
		[JsonProperty("sandbox")]
		public bool Sandbox { get; set; }
		[JsonProperty("quantity")]
		public int Quantity { get; set; }
		[JsonProperty("price")]
		public int Price { get; set; }
		[JsonProperty("discountedPrice")]
		public int DiscountedPrice { get; set; }
		[JsonProperty("tax")]
		public int Tax { get; set; }
		[JsonProperty("vat")]
		public int Vat { get; set; }
		[JsonProperty("salesTax")]
		public int SalesTax { get; set; }
		[JsonProperty("paymentProviderFee")]
		public int PaymentProviderFee { get; set; }
		[JsonProperty("paymentMethodFee")]
		public int PaymentMethodFee { get; set; }
		[JsonProperty("currency")]
		public CurrencyJson Currency { get; set; }
		[JsonProperty("itemSnapshot")]
		public ItemSnapshotJson ItemSnapshot { get; set; }
		[JsonProperty("region")]
		public string Region { get; set; }
		[JsonProperty("language")]
		public string Language { get; set; }
		[JsonProperty("status")]
		public string Status { get; set; }
		[JsonProperty("createdTime")]
		public string CreatedTime { get; set; }
		[JsonProperty("chargedTime")]
		public string ChargedTime { get; set; }
		[JsonProperty("fulfilledTime")]
		public string FulfilledTime { get; set; }
		[JsonProperty("expireTime")]
		public string ExpireTime { get; set; }
		[JsonProperty("paymentRemainSeconds")]
		public int PaymentRemainSeconds { get; set; }
		[JsonProperty("totalTax")]
		public int TotalTax { get; set; }
		[JsonProperty("totalPrice")]
		public int TotalPrice { get; set; }
		[JsonProperty("subtotalPrice")]
		public int SubtotalPrice { get; set; }
		[JsonProperty("createdAt")]
		public string CreatedAt { get; set; }
		[JsonProperty("updatedAt")]
		public string UpdatedAt { get; set; }
	}
}
